// This file is auto-generated. Do not edit manually.
//
// SPDX-FileCopyrightText: Generated by smufl_mapping (2026)
// SPDX-License-Identifier: MIT
//
// Source project: https://github.com/openmusx/smufl-mapping
//
// Generated from source_json/smufl_fonts.json by
// tools/generate_smufl_fonts_map.py
#pragma once

#include "smufl_mapping.h"

namespace smufl_mapping::detail {

struct SmuflFontRecord {
    std::string_view name;
    MusicFontType fontType;
    MusicFontStyle fontStyle;
    std::optional<double> staffSpacesPerEm;
    std::string_view sizeNotes;
};

constexpr std::pair<std::string_view, SmuflFontRecord> smuflFonts[] = {
    { "bravura", {"Bravura", MusicFontType::Engraving, MusicFontStyle::Engraved, 4.0, "A SMuFL music font spans four staff spaces per em by definition. Confirmed by the staff5Lines anchor (4.000)."} },
    { "bravuratext", {"Bravura Text", MusicFontType::Text, MusicFontStyle::Engraved, 5.0, "Follows the SMuFL text-font convention of five staff spaces per em, so a point size is NOT interchangeable with a music face. Confirmed by the staff5Lines anchor (4.998)."} },
    { "chaconneex", {"Chaconne Ex", MusicFontType::Engraving, MusicFontStyle::Engraved, 4.0, "A SMuFL music font spans four staff spaces per em by definition. Not available locally, so unverified by measurement."} },
    { "emmentaler", {"Emmentaler", MusicFontType::Engraving, MusicFontStyle::Engraved, 4.0, "A SMuFL music font spans four staff spaces per em by definition. MuseScore ships this font under the internal family name 'MScore', apparently to avoid colliding with a separately installed copy, and stores that name in score styles while showing the display name in its font menu. Its SMuFL metadata declares fontName 'Emmentaler'. Measured from that copy."} },
    { "emmentalertext", {"Emmentaler Text", MusicFontType::Text, MusicFontStyle::Engraved, 4.0, "Sits on the music em scale at four staff spaces per em rather than the five used by Bravura Text, so a point size is interchangeable with its music face. 319 measurements against Emmentaler fall within 1% of this convention, versus 2 for five. MuseScore ships this font under the internal family name 'MScore Text', apparently to avoid colliding with a separately installed copy, and stores that name in score styles while showing the display name in its font menu."} },
    { "finaleash", {"Finale Ash", MusicFontType::Engraving, MusicFontStyle::Handwritten, 4.0, "A SMuFL music font spans four staff spaces per em by definition. Confirmed by the staff5Lines anchor (4.019)."} },
    { "finaleashtext", {"Finale Ash Text", MusicFontType::Text, MusicFontStyle::Handwritten, std::nullopt, "Only 4 glyphs are shared with Finale Ash and none supports either convention."} },
    { "finalebroadway", {"Finale Broadway", MusicFontType::Engraving, MusicFontStyle::Handwritten, 4.0, "A SMuFL music font spans four staff spaces per em by definition. Confirmed by the staff5Lines anchor (4.019)."} },
    { "finalebroadwaylegacytext", {"Finale Broadway Legacy Text", MusicFontType::Text, MusicFontStyle::Handwritten, 4.0, "Sits on the music em scale at four staff spaces per em rather than the five used by Bravura Text, so a point size is interchangeable with its music face. All 64 measurements against Finale Broadway match exactly."} },
    { "finalebroadwaytext", {"Finale Broadway Text", MusicFontType::Text, MusicFontStyle::Handwritten, 4.0, "Sits on the music em scale at four staff spaces per em rather than the five used by Bravura Text, so a point size is interchangeable with its music face. 14 measurements fall within 1% of this against Finale Broadway and none within 1% of five spaces per em."} },
    { "finaleengraver", {"Finale Engraver", MusicFontType::Engraving, MusicFontStyle::Engraved, 4.0, "A SMuFL music font spans four staff spaces per em by definition. Confirmed by the staff5Lines anchor (3.996)."} },
    { "finalejazz", {"Finale Jazz", MusicFontType::Engraving, MusicFontStyle::Handwritten, 4.0, "A SMuFL music font spans four staff spaces per em by definition. Confirmed by the staff5Lines anchor (4.019)."} },
    { "finalejazztext", {"Finale Jazz Text", MusicFontType::Text, MusicFontStyle::Handwritten, 4.0, "Sits on the music em scale at four staff spaces per em rather than the five used by Bravura Text, so a point size is interchangeable with its music face. All 82 measurements against Finale Jazz match exactly."} },
    { "finalejazztextlowercase", {"Finale Jazz Text Lowercase", MusicFontType::Text, MusicFontStyle::Handwritten, 4.0, "Sits on the music em scale at four staff spaces per em rather than the five used by Bravura Text, so a point size is interchangeable with its music face. All 82 measurements against Finale Jazz match exactly."} },
    { "finalelegacy", {"Finale Legacy", MusicFontType::Engraving, MusicFontStyle::Engraved, 4.0, "A SMuFL music font spans four staff spaces per em by definition. Confirmed by the staff5Lines anchor (3.996)."} },
    { "finalemaestro", {"Finale Maestro", MusicFontType::Engraving, MusicFontStyle::Engraved, 4.0, "A SMuFL music font spans four staff spaces per em by definition. Confirmed by the staff5Lines anchor (4.047)."} },
    { "finalemaestrotext", {"Finale Maestro Text", MusicFontType::Text, MusicFontStyle::Engraved, 4.0, "Sits on the music em scale at four staff spaces per em rather than the five used by Bravura Text, so a point size is interchangeable with its music face. 50 measurements fall within 1% of this against Finale Maestro, versus 2 for five spaces per em."} },
    { "gonville", {"Gonville", MusicFontType::Engraving, MusicFontStyle::Engraved, 4.0, "A SMuFL music font spans four staff spaces per em by definition. MuseScore ships this font under the internal family name 'Gootville', apparently to avoid colliding with a separately installed copy, and stores that name in score styles while showing the display name in its font menu. Measured from that copy."} },
    { "gonvilletext", {"Gonville Text", MusicFontType::Text, MusicFontStyle::Engraved, 5.0, "Follows the SMuFL text-font convention of five staff spaces per em, so a point size is NOT interchangeable with a music face. 482 measurements against Gonville fall within 1% of this convention, versus 24 for four. MuseScore ships this font under the internal family name 'Gootville Text', apparently to avoid colliding with a separately installed copy, and stores that name in score styles while showing the display name in its font menu."} },
    { "leland", {"Leland", MusicFontType::Engraving, MusicFontStyle::Engraved, 4.0, "A SMuFL music font spans four staff spaces per em by definition. The font maps no staff5Lines glyph, so the value rests on the specification."} },
    { "lelandtext", {"Leland Text", MusicFontType::Text, MusicFontStyle::Engraved, 5.0, "Follows the SMuFL text-font convention of five staff spaces per em, so a point size is NOT interchangeable with a music face. 23 measurements fall within 1% of this convention against Leland and none within 1% of four spaces per em."} },
    { "musejazz", {"MuseJazz", MusicFontType::Engraving, MusicFontStyle::Handwritten, 4.0, "A SMuFL music font spans four staff spaces per em by definition. MuseScore's handwritten face; the handwritten classification matches denigma's existing MusicXmlFontFamilyFallback entry."} },
    { "musejazztext", {"MuseJazz Text", MusicFontType::Text, MusicFontStyle::Handwritten, 5.0, "Follows the SMuFL text-font convention of five staff spaces per em, so a point size is NOT interchangeable with a music face. 629 measurements against MuseJazz fall within 1% of this convention and none within 1% of four."} },
    { "petaluma", {"Petaluma", MusicFontType::Engraving, MusicFontStyle::Handwritten, 4.0, "A SMuFL music font spans four staff spaces per em by definition. The font maps no staff5Lines glyph, so the value rests on the specification."} },
    { "petalumascript", {"Petaluma Script", MusicFontType::Text, MusicFontStyle::Handwritten, std::nullopt, "Shares no SMuFL codepoints with Petaluma, leaving nothing to measure against."} },
    { "petalumatext", {"Petaluma Text", MusicFontType::Text, MusicFontStyle::Handwritten, 5.0, "Follows the SMuFL text-font convention of five staff spaces per em, so a point size is NOT interchangeable with a music face. Dominant scale against Petaluma is 1.250 in 35% of measurements."} },
    { "sebastian", {"Sebastian", MusicFontType::Engraving, MusicFontStyle::Engraved, 4.0, "A SMuFL music font spans four staff spaces per em by definition. Confirmed by the staff5Lines anchor (4.000)."} },
    { "sebastiantext", {"Sebastian Text", MusicFontType::Text, MusicFontStyle::Engraved, 5.0, "Follows the SMuFL text-font convention of five staff spaces per em, so a point size is NOT interchangeable with a music face. Confirmed by the staff5Lines anchor (4.998)."} },
};

} // namespace smufl_mapping::detail
