// This file is auto-generated. Do not edit manually.
//
// SPDX-FileCopyrightText: Generated by smufl_mapping (2026)
// SPDX-License-Identifier: MIT
//
// Source project: https://github.com/rpatters1/smufl-mapping
//
// Generated from tests/data/font_key_vectors.json by
// tools/generate_font_key_vectors.py
#pragma once

#include <string_view>

namespace smufl_mapping::test {

struct FontKeyVector {
    std::string_view raw;   // what a caller might pass in
    std::string_view key;   // what it must normalize to
    std::string_view note;  // why the row is here
};

inline constexpr FontKeyVector fontKeyVectors[] = {
    { "Maestro Wide", "maestrowide", "the ordinary case: fold case, drop the space" },
    { "maestrowide", "maestrowide", "already normalized; normalization is idempotent" },
    { "  MAESTRO   wide ", "maestrowide", "leading, interior and trailing runs all collapse away" },
    { "Finale\011Copyist\012Text\015", "finalecopyisttext", "tab, newline and carriage return are ASCII whitespace" },
    { "Maestro\013Wide\014", "maestrowide", "vertical tab and form feed complete the six ASCII whitespace chars" },
    { "", "", "empty in, empty out" },
    { "   ", "", "whitespace-only normalizes to the empty key, which matches nothing" },
    { "Maestro, Times", "maestro,times", "the comma survives; without it this would become 'maestrotimes', a real font, silently answering a MusicXML font-family list with the wrong face" },
    { "Bravura-Regular", "bravura-regular", "punctuation is not folded, so a PostScript name does not masquerade as its family" },
    { "Maestro\302\240Wide", "maestro\302\240wide", "U+00A0 NO-BREAK SPACE is NOT removed; Python's str.split() would have, the C++ never would, and the generator must not mint a key the runtime cannot reach" },
    { "Maestro\302\205Wide", "maestro\302\205wide", "U+0085 NEXT LINE: whitespace to Python's str.split(), not to this rule" },
    { "Maestro\343\200\200Wide", "maestro\343\200\200wide", "U+3000 IDEOGRAPHIC SPACE: likewise left alone" },
    { "Maestro\034Wide", "maestro\034wide", "U+001C FILE SEPARATOR is plain ASCII and still not whitespace here, though str.split() drops it" },
    { "Maestro\037Wide", "maestro\037wide", "U+001F UNIT SEPARATOR, same reasoning" },
    { "Kousaku Percussion", "kousakupercussion", "a real legacy font, so the C++ side can also confirm this key resolves" },
    { "MAESTROTIMES", "maestrotimes", "a real legacy font reached by an all-caps spelling" },
    { "Bravura Text", "bravuratext", "a real SMuFL registry font, exercising the same key on the registry side" },
    { "\303\204 Maestro", "\303\204maestro", "the leading A-umlaut stays UPPERCASE: only A-Z are folded. Python's str.lower() would have lowercased it, and std::tolower() under a Latin-1 locale would have rewritten bytes inside the UTF-8 sequence - either one would put a key in the table that the other language could never produce" },
    { "Gr\303\274\303\237e Wide", "gr\303\274\303\237ewide", "multi-byte UTF-8 survives intact, whether walked as characters or as bytes" },
};

} // namespace smufl_mapping::test
