// This file is generated from Opus.json
//
// SPDX-FileCopyrightText: Generated by smufl_mapping (2026)
// SPDX-License-Identifier: MIT
//
// Source project: https://github.com/rpatters1/smufl-mapping
//
// This header was generated from SMuFL font metadata provided by SMuFL and Finale
// and is part of the internal implementation of the smufl_mapping project.
//
// To regenerate this file, run tools/generate_glyphnames_map.py
#pragma once

#include "smufl_mapping.h"

namespace smufl_mapping::detail::legacy {

constexpr std::pair<char32_t, LegacyGlyphInfo> opusLegacyGlyphs[] = {
    {  34, { "caesura", 0xE4D1, "", SmuflGlyphSource::Smufl, false } },
    {  35, { "accidentalSharp", 0xE262, "", SmuflGlyphSource::Smufl, false } },
    {  37, { "segno", 0xE047, "", SmuflGlyphSource::Smufl, false } },
    {  38, { "gClef", 0xE050, "", SmuflGlyphSource::Smufl, false } },
    {  39, { "articStaccatissimoWedgeBelow", 0xE4A9, "", SmuflGlyphSource::Smufl, false } },
    {  42, { "keyboardPedalUp", 0xE655, "", SmuflGlyphSource::Smufl, false } },
    {  43, { "brassMuteClosed", 0xE5E5, "", SmuflGlyphSource::Smufl, false } },
    {  44, { "breathMarkComma", 0xE4CE, "", SmuflGlyphSource::Smufl, false } },
    {  45, { "articTenutoBelow", 0xE4A5, "", SmuflGlyphSource::Smufl, false } },
    {  46, { "augmentationDot", 0xE1E7, "", SmuflGlyphSource::Smufl, false } },
    {  47, { "unpitchedPercussionClef1", 0xE069, "", SmuflGlyphSource::Smufl, false } },
    {  48, { "timeSig0", 0xE080, "", SmuflGlyphSource::Smufl, false } },
    {  49, { "timeSig1", 0xE081, "", SmuflGlyphSource::Smufl, false } },
    {  50, { "timeSig2", 0xE082, "", SmuflGlyphSource::Smufl, false } },
    {  51, { "timeSig3", 0xE083, "", SmuflGlyphSource::Smufl, false } },
    {  52, { "timeSig4", 0xE084, "", SmuflGlyphSource::Smufl, false } },
    {  53, { "timeSig5", 0xE085, "", SmuflGlyphSource::Smufl, false } },
    {  54, { "timeSig6", 0xE086, "", SmuflGlyphSource::Smufl, false } },
    {  55, { "timeSig7", 0xE087, "", SmuflGlyphSource::Smufl, false } },
    {  56, { "timeSig8", 0xE088, "", SmuflGlyphSource::Smufl, false } },
    {  57, { "timeSig9", 0xE089, "", SmuflGlyphSource::Smufl, false } },
    {  62, { "articAccentAbove", 0xE4A0, "", SmuflGlyphSource::Smufl, false } },
    {  63, { "fClef", 0xE062, "", SmuflGlyphSource::Smufl, false } },
    {  66, { "cClef", 0xE05C, "", SmuflGlyphSource::Smufl, false } },
    {  67, { "timeSigCutCommon", 0xE08B, "", SmuflGlyphSource::Smufl, false } },
    {  69, { "note8thDown", 0xE1D8, "", SmuflGlyphSource::Smufl, false } },
    {  72, { "noteHalfDown", 0xE1D4, "", SmuflGlyphSource::Smufl, false } },
    {  74, { "flag8thDown", 0xE241, "", SmuflGlyphSource::Smufl, false } },
    {  75, { "flagInternalUp", 0xE250, "", SmuflGlyphSource::Smufl, false } },
    {  77, { "ornamentMordent", 0xE56D, "", SmuflGlyphSource::Smufl, false } },
    {  79, { "noteheadDiamondHalf", 0xE0D9, "", SmuflGlyphSource::Smufl, false } },
    {  81, { "noteQuarterDown", 0xE1D6, "", SmuflGlyphSource::Smufl, false } },
    {  82, { "flag16thDown", 0xE243, "", SmuflGlyphSource::Smufl, false } },
    {  84, { "ornamentTurn", 0xE567, "", SmuflGlyphSource::Smufl, false } },
    {  85, { "fermataAbove", 0xE4C0, "", SmuflGlyphSource::Smufl, false } },
    {  87, { "noteDoubleWhole", 0xE1D0, "", SmuflGlyphSource::Smufl, false } },
    {  88, { "note16thDown", 0xE1DA, "", SmuflGlyphSource::Smufl, false } },
    {  94, { "articMarcatoAbove", 0xE4AC, "", SmuflGlyphSource::Smufl, false } },
    {  98, { "accidentalFlat", 0xE260, "", SmuflGlyphSource::Smufl, false } },
    {  99, { "timeSigCommon", 0xE08A, "", SmuflGlyphSource::Smufl, false } },
    { 101, { "note8thUp", 0xE1D7, "", SmuflGlyphSource::Smufl, false } },
    { 104, { "noteHalfUp", 0xE1D3, "", SmuflGlyphSource::Smufl, false } },
    { 106, { "flag8thUp", 0xE240, "", SmuflGlyphSource::Smufl, false } },
    { 109, { "ornamentShortTrill", 0xE56C, "", SmuflGlyphSource::Smufl, false } },
    { 110, { "accidentalNatural", 0xE261, "", SmuflGlyphSource::Smufl, false } },
    { 111, { "stringsHarmonic", 0xE614, "", SmuflGlyphSource::Smufl, false } },
    { 113, { "noteQuarterUp", 0xE1D5, "", SmuflGlyphSource::Smufl, false } },
    { 114, { "flag16thUp", 0xE242, "", SmuflGlyphSource::Smufl, false } },
    { 117, { "fermataBelow", 0xE4C1, "", SmuflGlyphSource::Smufl, false } },
    { 118, { "articMarcatoBelow", 0xE4AD, "", SmuflGlyphSource::Smufl, false } },
    { 119, { "noteheadWhole", 0xE0A2, "", SmuflGlyphSource::Smufl, false } },
    { 120, { "note16thUp", 0xE1D9, "", SmuflGlyphSource::Smufl, false } },
    { 126, { "wiggleTrill", 0xEAA4, "", SmuflGlyphSource::Smufl, false } },
    { 161, { "keyboardPedalPed", 0xE650, "", SmuflGlyphSource::Smufl, false } },
    { 168, { "rest32nd", 0xE4E8, "", SmuflGlyphSource::Smufl, false } },
    { 174, { "articStaccatissimoWedgeAbove", 0xE4A8, "", SmuflGlyphSource::Smufl, false } },
    { 178, { "stringsUpBow", 0xE612, "", SmuflGlyphSource::Smufl, false } },
    { 179, { "stringsDownBow", 0xE610, "", SmuflGlyphSource::Smufl, false } },
    { 181, { "ornamentTremblement", 0xE56E, "", SmuflGlyphSource::Smufl, false } },
    { 183, { "restWhole", 0xE4E3, "", SmuflGlyphSource::Smufl, false } },
    { 186, { "accidentalDoubleFlat", 0xE264, "", SmuflGlyphSource::Smufl, false } },
    { 192, { "timeSigMultiply", 0xE091, "", SmuflGlyphSource::Smufl, false } },
    { 197, { "rest16th", 0xE4E7, "", SmuflGlyphSource::Smufl, false } },
    { 206, { "restQuarter", 0xE4E5, "", SmuflGlyphSource::Smufl, false } },
    { 207, { "noteheadBlack", 0xE0A4, "", SmuflGlyphSource::Smufl, false } },
    { 212, { "repeat1Bar", 0xE500, "", SmuflGlyphSource::Smufl, false } },
    { 214, { "unpitchedPercussionClef2", 0xE06A, "", SmuflGlyphSource::Smufl, false } },
    { 217, { "ornamentTrill", 0xE566, "", SmuflGlyphSource::Smufl, false } },
    { 220, { "accidentalDoubleSharp", 0xE263, "", SmuflGlyphSource::Smufl, false } },
    { 221, { "noteheadDoubleWholeSquare", 0xE0A1, "", SmuflGlyphSource::Smufl, false } },
    { 222, { "coda", 0xE048, "", SmuflGlyphSource::Smufl, false } },
    { 226, { "noteheadDiamondBlack", 0xE0DB, "", SmuflGlyphSource::Smufl, false } },
    { 228, { "rest8th", 0xE4E6, "", SmuflGlyphSource::Smufl, false } },
    { 229, { "rest128th", 0xE4EA, "", SmuflGlyphSource::Smufl, false } },
    { 238, { "restHalf", 0xE4E4, "", SmuflGlyphSource::Smufl, false } },
    { 239, { "flag8thDown", 0xE241, "", SmuflGlyphSource::Smufl, false } },
    { 244, { "rest64th", 0xE4E9, "", SmuflGlyphSource::Smufl, false } },
    { 250, { "noteheadHalf", 0xE0A3, "", SmuflGlyphSource::Smufl, false } },
};

} // namespace smufl_mapping::detail::legacy
