#!/usr/bin/env python3
"""Generate src/detail/smufl_fonts.h from source_json/smufl_fonts.json."""

import sys
from datetime import datetime
from pathlib import Path

from font_keys import normalize_font_key
from json_utils import load_json_strict

BASE_DIR = Path(__file__).resolve().parent.parent
SOURCE_FILE = BASE_DIR / "source_json" / "smufl_fonts.json"
OUTPUT_HEADER = BASE_DIR / "src" / "detail" / "smufl_fonts.h"

FONT_TYPE_ENUM = {
    "engraving": "MusicFontType::Engraving",
    "text": "MusicFontType::Text",
}
FONT_STYLE_ENUM = {
    "engraved": "MusicFontStyle::Engraved",
    "handwritten": "MusicFontStyle::Handwritten",
}


def cpp_string_literal(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', '\\"')


def main() -> int:
    with SOURCE_FILE.open("r", encoding="utf-8") as handle:
        fonts = load_json_strict(handle, location=str(SOURCE_FILE))

    rows = sorted(
        ((normalize_font_key(name), name, props) for name, props in fonts.items()),
        key=lambda row: row[0],
    )

    OUTPUT_HEADER.parent.mkdir(parents=True, exist_ok=True)
    with OUTPUT_HEADER.open("w", encoding="utf-8") as out:
        out.write("// This file is auto-generated. Do not edit manually.\n")
        out.write("//\n")
        out.write(f"// SPDX-FileCopyrightText: Generated by smufl_mapping ({datetime.now().year})\n")
        out.write("// SPDX-License-Identifier: MIT\n")
        out.write("//\n")
        out.write("// Source project: https://github.com/openmusx/smufl-mapping\n")
        out.write("//\n")
        out.write("// Generated from source_json/smufl_fonts.json by\n")
        out.write("// tools/generate_smufl_fonts_map.py\n")
        out.write('#pragma once\n\n')
        out.write('#include "smufl_mapping.h"\n\n')
        out.write('namespace smufl_mapping::detail {\n\n')
        out.write('struct SmuflFontRecord {\n')
        out.write('    std::string_view name;\n')
        out.write('    MusicFontType fontType;\n')
        out.write('    MusicFontStyle fontStyle;\n')
        out.write('    std::optional<double> staffSpacesPerEm;\n')
        out.write('    std::string_view sizeNotes;\n')
        out.write('};\n\n')
        out.write('constexpr std::pair<std::string_view, SmuflFontRecord> smuflFonts[] = {\n')
        for key, name, props in rows:
            spaces = props["staffSpacesPerEm"]
            spaces_literal = "std::nullopt" if spaces is None else f"{float(spaces)!r}"
            out.write(
                f'    {{ "{key}", {{"{cpp_string_literal(name)}", '
                f'{FONT_TYPE_ENUM[props["fontType"]]}, {FONT_STYLE_ENUM[props["fontStyle"]]}, '
                f'{spaces_literal}, "{cpp_string_literal(props.get("sizeNotes", ""))}"}} }},\n'
            )
        out.write('};\n\n')
        out.write('} // namespace smufl_mapping::detail\n')

    print(f"Generated {OUTPUT_HEADER.relative_to(BASE_DIR)} with {len(rows)} font(s).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
