#!/usr/bin/env python3
"""Generate tests/font_key_vectors.h from tests/data/font_key_vectors.json.

The JSON is the single source of truth for how a font name normalizes. Python
can read it directly; C++ cannot, since the library deliberately has no JSON
parser, so the rows are emitted as a constexpr table for the gtest to walk.

The generated header is checked in, matching how the rest of the project ships
pregenerated headers so that a build needs no Python. `tests/font_key_test.py`
regenerates it in memory and fails if the checked-in copy has drifted.
"""

import sys
from datetime import datetime
from pathlib import Path

from json_utils import load_json_strict

BASE_DIR = Path(__file__).resolve().parent.parent
SOURCE_FILE = BASE_DIR / "tests" / "data" / "font_key_vectors.json"
OUTPUT_HEADER = BASE_DIR / "tests" / "font_key_vectors.h"


def cpp_string_literal(text: str) -> str:
    """Render a Python str as the body of a C++ UTF-8 string literal.

    Every byte outside printable ASCII becomes a three-digit octal escape.
    Octal escapes are used rather than \\x because \\x consumes *all* following
    hex digits, so "\\x1cWide" would be read as one enormous character constant;
    an octal escape stops after three digits and cannot run on into the text.
    """
    out = []
    for byte in text.encode("utf-8"):
        ch = chr(byte)
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif 0x20 <= byte < 0x7F:
            out.append(ch)
        else:
            out.append("\\%03o" % byte)
    return "".join(out)


def main() -> int:
    with SOURCE_FILE.open("r", encoding="utf-8") as handle:
        data = load_json_strict(handle, location=str(SOURCE_FILE))

    return 0 if write_header(data, OUTPUT_HEADER) else 1


def render(data: dict) -> str:
    """Return the full text of the generated header."""
    lines = []
    add = lines.append
    add("// This file is auto-generated. Do not edit manually.")
    add("//")
    add(f"// SPDX-FileCopyrightText: Generated by smufl_mapping ({datetime.now().year})")
    add("// SPDX-License-Identifier: MIT")
    add("//")
    add("// Source project: https://github.com/rpatters1/smufl-mapping")
    add("//")
    add("// Generated from tests/data/font_key_vectors.json by")
    add("// tools/generate_font_key_vectors.py")
    add("#pragma once")
    add("")
    add("#include <string_view>")
    add("")
    add("namespace smufl_mapping::test {")
    add("")
    add("struct FontKeyVector {")
    add("    std::string_view raw;   // what a caller might pass in")
    add("    std::string_view key;   // what it must normalize to")
    add("    std::string_view note;  // why the row is here")
    add("};")
    add("")
    add("inline constexpr FontKeyVector fontKeyVectors[] = {")
    for vector in data["vectors"]:
        add("    { \"%s\", \"%s\", \"%s\" }," % (
            cpp_string_literal(vector["raw"]),
            cpp_string_literal(vector["key"]),
            cpp_string_literal(vector["note"]),
        ))
    add("};")
    add("")
    add("} // namespace smufl_mapping::test")
    add("")
    return "\n".join(lines)


def write_header(data: dict, output: Path) -> bool:
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render(data), encoding="utf-8")
    print(f"Wrote {output} ({len(data['vectors'])} vectors).")
    return True


if __name__ == "__main__":
    sys.exit(main())
